config/routes.rb
SqlPql::Application.routes.draw do
  use_doorkeeper

  root :to => 'static_pages#index'
  get 'lesson/:id' => 'static_pages#lesson'
  get 'auth/:provider/callback' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'run' => 'sql#run'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  provider   :string(255)      not null
#  uid        :string(255)      not null
#  nickname   :string(255)
#  name       :string(255)
#  email      :string(255)
#  avatar_url :string(255)
#

class User < ActiveRecord::Base
  validates :provider, :uid, presence: true
  validates :uid, uniqueness: true

  def self.from_omniauth(auth)
    provider = auth['provider']
    uid = auth['uid']
    user = User.find_by_provider_and_uid(provider, uid)
    if (user)
      return user
    else
      user = User.new
      user.provider = provider
      user.uid = uid
      info = auth['info']
      user.nickname = info['nickname']
      user.name = info['name']
      user.email = info['email']
      user.avatar_url = info['image']
      user.save!
      return user
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    flash[:success] = ["Successfully logged in as #{user.nickname}"]
    redirect_to '/lesson/0'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/sql_controller.rb
class SqlController < ApplicationController
	def run
    # sleep 1
    query = params['query']
    answer = params['answer']

    blacklist = %w(DROP INSERT UPDATE CREATE ALTER DELETE TRUNCATE)

    blacklist.each do |word|
    	if query.upcase.include?(word) || answer.upcase.include?(word)
        # return render :json => {status: "\"#{word}\" is blacklisted!"}
        redirect_to 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CDgQtwIwAQ&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DoHg5SJYRHA0&ei=RNg1U9C6M5TlygHJ6YCQCw&usg=AFQjCNEcy3X8QxEz3ZqmxAznmt4YfNijBQ&sig2=8XcMNbm7EiyUUkpwJDGumQ&bvm=bv.63808443,d.aWc' and return
    	end
    end

    pg_result = nil
    db = nil

    config = Rails.configuration.database_configuration[Rails.env]
    database = config['database']
    if Rails.env.production?
    	host = config['host']
    	port = config['port']
    	user = config['username']
    	password = config['password']
    	db = PG::Connection.open(host: host, port: port, dbname: database, user: user, password: password)
    else
    	db = PG::Connection.open(dbname: database)
    end

    begin
    	pg_result = db.exec_params(query)
    rescue PGError => e
    	db.close
    	return render :json => {error: e.message}
    end


    if answer.empty?
    	render :json => {fields: pg_result.fields, rows:pg_result.values}
    else
    	pg_answer = db.exec_params(answer)
    	status = compare_results(pg_result, pg_answer)
    	render :json => {fields: pg_result.fields, rows:pg_result.values, status: status}
    end
    db.close
end

def compare_results(result, answer)
	if result.ntuples < answer.ntuples
		return 'Result has too few rows'
	elsif result.ntuples > answer.ntuples
		return 'Result has too many rows'
	elsif result.nfields < answer.nfields
		return 'Result has too few columns'
	elsif result.nfields > answer.nfields
		return 'Result has too many columns'
	end

	for i in 0...result.ntuples
		r_row = result[i]
		a_row = answer[i]
		return "Result don't match" if r_row.values != a_row.values
	end

	return 'Correct!'
end

private
def sanitize(str)
	balcklist = %w(drop, insert, update, set)
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def lesson
    filename = "lesson_#{params[:id].to_i.to_words}.yaml"
    filepath = Rails.root.to_s + "/app/assets/lessons/#{filename}"
    lesson = YAML.load_file(filepath)

    @title = lesson[:title]
    @sections = lesson[:sections]
    @next_lesson = lesson[:next_lesson]

    if params[:id] == '0'
      render :lesson_zero
    else
      render :lesson_view
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    user_id = session[:user_id]
    if (user_id)
      @user ||= User.find(user_id)
    else
      @user = nil
    end
  end


end

app/helpers/sql_helper.rb
module SqlHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SQL-PQL</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Ruluko' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="border-radius:0 !important">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="<%= root_url %>">SQL-PQL</a>


	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<% if current_user %>
	      <ul class="nav navbar-nav">
					<li class="hidden-xs"><img src="<%= current_user.avatar_url %>" width="50px" height="50px"></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Welcome, <%= current_user.nickname %> <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Log out', logout_url, method: 'delete' %></li>
						</ul>

					</li>
				</ul>
				<% end %>

	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="<%= root_url %>">Home</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lessons <b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><a href="/lesson/0">0. Intro to world of SQL</a></li>
	            <li><a href="/lesson/1">1. The SELECT command</a></li>
	            <li><a href="/lesson/2">2. Lets SUM, COUNT, MAX and more!</a></li>
	            <li><a href="/lesson/3">3. Subqueries, SELECT inception</a></li>
	          </ul>
	        </li>

	        <li class="dropdown keep-open hidden-xs">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-list"></span> Show Table <b class="caret"></b></a>
	          <ul class="dropdown-menu dropdown-table semi-transparent">
	          	<div class="">

	          		<%= render 'world_table' %>

	          	</div>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<%= yield %>

<hr>
<div class="row footer">
	SQL-PQL by Minh Luu
</div>
<hr>
</body>
</html>

app/views/static_pages/_alert_view.html.erb
<div class="row">
	<div class="col-md-8 col-md-2-offset">
<% if flash[:success] %>
<% flash[:success].each do |success| %>
	<div class="alert alert-wraning alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= success %>
	</div>
<% end %>
<% end %>

<% if flash[:notice] %>
<% flash[:notice].each do |notice| %>
	<div class="alert alert-wraning alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= notice %>
	</div>
<% end %>
<% end %>

<% if flash[:errors] %>
<% flash[:errors].each do |error| %>
	<div class="alert alert-danger alert alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= error %>
	</div>
<% end %>
<% end %>
</div>
</div>

app/views/static_pages/_section_view.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs top-buffer">
	<% section.each do |item| %>
		<li <%= 'class=active' if section.first == item %>>
			<a href="#<%= item[:id] %>" data-toggle="tab">
				<strong>
					<%= item[:title] %>
				</strong>
			</a>
		</li>
	<% end %>
</ul>

<!-- Tab panes -->
<div class="tab-content top-buffer">
	<% section.each do |item| %>
		<div class="tab-pane <%= 'active' if section.first == item %>" id="<%= item[:id] %>">
			<%= render 'sql_view',
				content: item[:content],
				query: item[:query],
				answer: item[:answer]
			%>
		</div>
	<% end %>
</div>

app/views/static_pages/_sql_view.html.erb
<div class="row">

	<div class="col-sm-5 input-window">
		<% if content %>
		<p><%= content.html_safe %></p>
		<% end %>
		<form>
			<div class="form-group">
				<textarea class="sql-input" placeholder="Type query here..."  data-answer="<%= answer %>"><%= query %></textarea>
			</div>
			<div class="form-group text-right">
				<% if answer %>
					<input type="button" class="show-answer btn btn-default" value="Show Answer">
				<% end %>
				<input type="submit" class="btn btn-primary">
			</div>
		</form>
	</div>

	<div class="col-sm-7 well output-window">
		<div class="output-text">
			<h3>Output Screen</h3>
			<p>Press <span class="label label-default" style="opacity: 0.3">submit</span> to see result</p>
		</div>
	</div>
</div>

app/views/static_pages/_sql_window.html.erb
<div class="row">

	<div class="col-sm-5 input-window">
		<p><%= content %></p>
		<form>
			<div class="form-group">
				<textarea class="sql-input" placeholder="Type query here..."  data-answer="<%= answer %>"><%= query %></textarea>
			</div>
			<div class="form-group text-right">
				<% if answer %>
					<input type="button" class="show-answer btn btn-default" value="Show Answer">
				<% end %>
				<input type="submit" class="btn btn-primary">
			</div>
		</form>
	</div>

	<div class="col-sm-6 well output-window">
		<div class="output-text">
			<h3>Output Screen</h3>
			<p>Press "submit" to see result</p>
		</div>
	</div>
</div>

app/views/static_pages/_tab_view.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs top-buffer">
	<% section.each do |item| %>
		<li <%= 'class=active' if section.first == item %>>
			<a href="#<%= item[:id] %>" data-toggle="tab">
				<strong>
					<%= item[:title] %>
				</strong>
			</a>
		</li>
	<% end %>
</ul>

<!-- Tab panes -->
<div class="tab-content top-buffer">
	<% section.each do |item| %>
		<div class="tab-pane <%= 'active' if section.first == item %>" id="<%= item[:id] %>">
			<%= render 'sql_window',
				content: item[:content],
				query: item[:query],
				answer: item[:answer]
			%>
		</div>
	<% end %>
</div>

app/views/static_pages/_world_table.html.erb
<div class="text-center">
<h5>Table Name: world</h5>
</div>

<table class="table table-striped">

<tbody><tr>

	  <th>name</th>

	  <th>region</th>

	  <th>area</th>

	  <th>population</th>

	  <th>gdp</th>

</tr>


	<tr>

		  <td>Afghanistan</td>

		  <td>South Asia</td>

		  <td>652,225</td>

		  <td>26,000,000</td>

		  <td>0</td>

	</tr>

	<tr>

		  <td>Albania</td>

		  <td>Europe</td>

		  <td>28,728</td>

		  <td>3,200,000</td>

		  <td>6,656,000,000</td>

	</tr>

	<tr>

		  <td>Algeria</td>

		  <td>Middle East</td>

		  <td>2,400,000</td>

		  <td>32,900,000</td>

		  <td>75,012,000,000</td>

	</tr>

	<tr class="short-row">
		  <td>...</td>
		  <td>...</td>
		  <td>...</td>
		  <td>...</td>
		  <td>...</td>
	</tr>

	<tr>

		  <td>Zambia</td>

		  <td>Africa</td>

		  <td>752,614</td>

		  <td>11,000,000</td>

		  <td>4,950,000,000</td>

	</tr>

	<tr>

		  <td>Zimbabwe</td>

		  <td>Africa</td>

		  <td>390,759</td>

		  <td>12,900,000</td>

		  <td>6,192,000,000</td>

	</tr>

</tbody></table>
<div class="text-right show-table-footer">
<small>Note: table is compressed.</small>
</div>

app/views/static_pages/index.html.erb
<style>
.intro {
	height: 500px;
	padding-top: 200px;
	text-align: center;
	background: url('<%= image_url("wheat7.jpg") %>');
	background-size: cover;
	color: white;
}
</style>

<div class="jumbotron intro">
  <h1>Hello there!</h1>
  <p>Welcome to SQL-PQL ("sequel prequel") an interactive SQL learning guide.</p>
  <p><a class="btn btn-lg btn-success" href="lesson/0">Start Learning</a></p>
	<% if current_user.nil? %>
		<p><a class="btn btn-lg btn-primary" href="auth/github">Login with GitHub</a></p>
	<% end %>

</div>

app/views/static_pages/lesson_view.html.erb
<div class="container">

	<!-- <%= render 'alert_view' %> -->

<div class="row">
	<h1 class="page-header"><%= @title %></h1>
</div>


<% @sections.each do |section| %>
	<%= render 'section_view', section: section %>
<% end %>

<!-- Next lesson button -->
<% if @next_lesson %>
	<div class="row text-right">
		<a class="btn btn-success" href="<%= @next_lesson[:link] %>"><%= @next_lesson[:title] %></a>
	</div>
<% end %>
</div>

app/views/static_pages/lesson_zero.html.erb
<div class="container">

	<!-- <%= render 'alert_view' %> -->

	<div class="row">
		<h1 class="page-header">0. The world of SQL</h1>
	</div>

	<div class="row">
		<div class="panel panel-default col col-md-8 col-md-offset-2">
			<div class="panel-body">
				<h3>What is SQL?</h3>
				<ul>
					<li>SQL stands for Structured Query Language</li>
					<li>SQL lets you access and manipulate databases</li>
					<li>SQL is an ANSI (American National Standards Institute) standard</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="panel panel-default col col-md-8 col-md-offset-2">
			<div class="panel-body">
				<h3>What Can SQL do?</h3>
				<ul>
					<li>SQL can execute queries against a database</li>
					<li>SQL can retrieve data from a database</li>
					<li>SQL can insert records in a database</li>
					<li>SQL can update records in a database</li>
					<li>SQL can delete records from a database</li>
					<li>SQL can create new databases</li>
					<li>SQL can create new tables in a database</li>
					<li>SQL can create stored procedures in a database</li>
					<li>SQL can create views in a database</li>
					<li>SQL can set permissions on tables, procedures, and views</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="panel panel-default col col-md-8 col-md-offset-2">
			<div class="panel-body">
				The table you'll be working with is called <span class="badge">world</span>. Here is a <strong>compressed sample</strong> of the table. You can also get a preview the table anywhere by pressing <span class="label label-default"><span class="glyphicon glyphicon-list"></span> Show Table <b class="caret"></b></span> in the navigation bar above. Give it a try now! <small><i>(Note: "show table" isn't available on small screens.)</i></small>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="well col col-md-8 col-md-offset-2">
			<%= render 'world_table' %>
		</div>
	</div>

	<% @sections.each do |section| %>
	<%= render 'section_view', section: section %>
	<% end %>

	<div class="row text-right">
		<a class="btn btn-success" href="1">1. The SELECT command</a>
	</div>
</div>

app/views/static_pages/section_view.html.erb
<div class="container">
<div class="row">
	<h1 class="page-header"><%= @section_title %></h1>
</div>


<% @lesson.each do |section| %>
	<%= render 'tab_view', section: section %>
<% end %>
</div>